services:
  web:
    build: .
    image: peliculas-app:1.0
    container_name: peliculas_web
    ports:
      - "8080:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: peliculas
      DB_USER: peliculas_user
      DB_PASSWORD: peliculas_pass
    depends_on:
      db:
        condition: service_healthy
    networks:
      - peliculas-net

  db:
    image: postgres:16-alpine
    container_name: peliculas_db
    environment:
      POSTGRES_DB: peliculas
      POSTGRES_USER: peliculas_user
      POSTGRES_PASSWORD: peliculas_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peliculas_user -d peliculas"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - peliculas-net

networks:
  peliculas-net:

volumes:
  pgdata: